### ISSUE TITLE
Cloud NAT is created in wrong VPC

### ISSUE THREAD

**Issue by yingjie-wang-mpf** [wwce/google-cloud-vmseries-builds#1]
for /blueprints/vmseries-hub-spoke-autoscale, you've assigned public IP on mgmt interface, so by default, all the outbound traffic will go through that IP instead of cloud NAT on the mgmt vpc, making it redundant. However, in the same time, you didn't create either cloud NAT in untrust vpc or public IP on untrust interface, so there's no way for spoke assets to access internet

**Comment by mattmclimans** [comment]
Thank you for reporting this.  The blueprints/vmseries-hub-spoke-autoscale has been modified to include a Cloud NAT in the untrust VPC and management VPC networks.  The external IP addresses on the management interfaces and on the untrust interfaces have been removed.
